// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdkNetCoreCRUD.Data;

#nullable disable

namespace PdkNetCoreLab12EF.Migrations
{
    [DbContext(typeof(PdkAppDbContext))]
    partial class PdkAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PdkNetCoreCRUD.Models.PdkCategory", b =>
                {
                    b.Property<int>("PdkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdkId"));

                    b.Property<DateTime>("PdkCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdkName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("PdkStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdkId");

                    b.ToTable("PdkCategory");
                });

            modelBuilder.Entity("PdkNetCoreCRUD.Models.PdkProduct", b =>
                {
                    b.Property<int>("PdkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdkId"));

                    b.Property<int>("PdkCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PdkCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdkDescriptions")
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("PdkImage")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PdkName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("PdkPrice")
                        .HasColumnType("real");

                    b.Property<float>("PdkSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("PdkStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdkId");

                    b.HasIndex("PdkCategoryId");

                    b.ToTable("PdkProduct");
                });

            modelBuilder.Entity("PdkNetCoreCRUD.Models.PdkProduct", b =>
                {
                    b.HasOne("PdkNetCoreCRUD.Models.PdkCategory", "PdkCategory")
                        .WithMany("PdkProducts")
                        .HasForeignKey("PdkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdkCategory");
                });

            modelBuilder.Entity("PdkNetCoreCRUD.Models.PdkCategory", b =>
                {
                    b.Navigation("PdkProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
