// <auto-generated />
using System;
using BTVN_PdkLab12.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTVN_PdkLab12.Migrations
{
    [DbContext(typeof(PdkDbContext))]
    partial class PdkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTVN_PdkLab12.Models.PdkCategory", b =>
                {
                    b.Property<int>("PdkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdkId"));

                    b.Property<DateTime>("PdkCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("PdkStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdkId");

                    b.ToTable("PdkCategories");
                });

            modelBuilder.Entity("BTVN_PdkLab12.Models.PdkProduct", b =>
                {
                    b.Property<int>("PdkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PdkId"));

                    b.Property<int>("PdkCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PdkCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdkDescriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdkImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdkName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PdkPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PdkSalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte>("PdkStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("PdkId");

                    b.HasIndex("PdkCategoryId");

                    b.ToTable("PdkProducts");
                });

            modelBuilder.Entity("BTVN_PdkLab12.Models.PdkProduct", b =>
                {
                    b.HasOne("BTVN_PdkLab12.Models.PdkCategory", "PdkCategory")
                        .WithMany("PdkProducts")
                        .HasForeignKey("PdkCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PdkCategory");
                });

            modelBuilder.Entity("BTVN_PdkLab12.Models.PdkCategory", b =>
                {
                    b.Navigation("PdkProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
